[package]
name = "vec"
version = "0.1.0"
authors = ["molok"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lerp = {path = "../../lib/lerp"}