[package]
name = "collider"
version = "0.1.0"
authors = ["molok"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vec = {path = "../vec"}
lerp = {path = "../../lib/lerp"}
angular = "0.1.1"